# YAML EXPLANATION FILE #

Name: Mr.Kronos
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++,Java
Python-Version: Python 3 
Original Creator: Aryan
Author: Aryan
Copyright: (C) 2021-2026 Aryan <mr.kronos@proton.me>
Copyright-Years: 2021,2022,2023,2024,2025,2026
Project-site: https://mrkronos.github.io/Mr.Kronos
Download: git clone https://github.com/aryanhubhaimai/Mr.Kronos-OSINT
Platforms: Linux/MacOS/Termux/Windows
Version: T.G.D-1.0.4
License: GNU General Public License v3.0
